FROM python:3.9-slim

# Instala AWS SAM CLI
RUN pip install --no-cache-dir aws-sam-cli

# Directorio de trabajo donde estará tu proyecto
WORKDIR /app

# Copiar plantilla y código compilado
COPY template.yml /app/
COPY bin/ /app/bin/

# (Opcional) Precompilar SAM para acelerar start-api
# RUN sam build --cached --use-container

# Por defecto arrancamos SAM al iniciar el contenedor
ENTRYPOINT ["sam"]
CMD ["local", "start-api", "--host", "0.0.0.0", "--port", "3000", "--docker-network", "app-network"]
